# Generated by Django 6.0.4 on 2026-04-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hotel Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(choices=[('zanzibar', 'Zanzibar'), ('dar_es_salaam', 'Dar es Salaam')], max_length=20, verbose_name='Location')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (French)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (Russian)')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Star Rating')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Night (USD)')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tripadvisor_url', models.URLField(blank=True, null=True, verbose_name='TripAdvisor URL')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Approval Status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_cover', models.BooleanField(default=False, verbose_name='Cover Photo')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.hotel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Type Name')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Per Night (USD) — overrides hotel base price if set')),
                ('max_guests', models.PositiveIntegerField(verbose_name='Max Guests')),
                ('amenities', models.JSONField(default=list, help_text='List of amenity strings e.g. ["WiFi", "AC", "Pool view"]', verbose_name='Amenities')),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['price_per_night'],
            },
        ),
    ]
