# Generated by Django 6.0.4 on 2026-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='allows_pay_on_arrival',
            field=models.BooleanField(default=True, help_text='If unchecked, only Pay Now is accepted for this room type.', verbose_name='Allows Pay on Arrival'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='discount_expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank for a permanent discount.', null=True, verbose_name='Discount Expires At'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = no discount. Applied to the effective price per night.', verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='If unchecked, this room is non-refundable regardless of cancellation policy.', verbose_name='Refundable'),
        ),
    ]
