# Generated by Django 6.0.4 on 2026-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelroomtype_allows_pay_on_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='allows_pets',
            field=models.BooleanField(default=False, help_text='If unchecked, pets are not permitted in this room type.', verbose_name='Pets Allowed'),
        ),
        migrations.AlterField(
            model_name='hotelroomtype',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='If unchecked, non-refundable regardless of cancellation policy.', verbose_name='Refundable'),
        ),
        migrations.AlterField(
            model_name='hotelroomtype',
            name='max_guests',
            field=models.PositiveIntegerField(verbose_name='Max Guests Per Room'),
        ),
    ]
