# Generated by Django 6.0.4 on 2026-05-27 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_add_allows_pets_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomTypePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/room_photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='hotels.hotelroomtype')),
            ],
            options={
                'verbose_name': 'Room Type Photo',
                'verbose_name_plural': 'Room Type Photos',
                'ordering': ['order'],
            },
        ),
    ]
