# Generated by Django 6.0.4 on 2026-04-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (French)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Russian)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tour_type', models.CharField(choices=[('safari', 'Safari'), ('beach', 'Beach'), ('cultural', 'Cultural'), ('climbing', 'Climbing'), ('combined', 'Combined Safari & Beach')], max_length=20, verbose_name='Tour Type')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration (Days)')),
                ('group_size_max', models.PositiveIntegerField(verbose_name='Maximum Group Size')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Person (USD)')),
                ('highlights_en', models.JSONField(default=list, verbose_name='Highlights (English)')),
                ('highlights_fr', models.JSONField(blank=True, default=list, null=True)),
                ('highlights_ru', models.JSONField(blank=True, default=list, null=True)),
                ('inclusions_en', models.JSONField(default=list, verbose_name='Inclusions (English)')),
                ('inclusions_fr', models.JSONField(blank=True, default=list, null=True)),
                ('inclusions_ru', models.JSONField(blank=True, default=list, null=True)),
                ('exclusions_en', models.JSONField(default=list, verbose_name='Exclusions (English)')),
                ('exclusions_fr', models.JSONField(blank=True, default=list, null=True)),
                ('exclusions_ru', models.JSONField(blank=True, default=list, null=True)),
                ('what_to_bring_en', models.TextField(blank=True, null=True)),
                ('what_to_bring_fr', models.TextField(blank=True, null=True)),
                ('what_to_bring_ru', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(upload_to='tours/covers/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in Featured Packages section on homepage', verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TourItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Day Number')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
