# Generated by Django 6.0.4 on 2026-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourpackage_allows_pay_on_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='allows_pets',
            field=models.BooleanField(default=False, help_text='If unchecked, pets are not permitted on this tour.', verbose_name='Pets Allowed'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='allows_pay_on_arrival',
            field=models.BooleanField(default=True, verbose_name='Allows Pay on Arrival'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='discount_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_refundable',
            field=models.BooleanField(default=True, verbose_name='Refundable'),
        ),
    ]
