# Generated by Django 6.0.4 on 2026-04-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vehicle Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('minibus', 'Minibus'), ('4x4', '4x4 Safari'), ('van', 'Van')], max_length=10, verbose_name='Vehicle Type')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('capacity', models.PositiveIntegerField(verbose_name='Passenger Capacity')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Day (USD)')),
                ('offers_self_drive', models.BooleanField(default=False, verbose_name='Offers Self-Drive')),
                ('offers_driver', models.BooleanField(default=True, verbose_name='Offers Driver')),
                ('driver_speaks_en', models.BooleanField(default=True, verbose_name='Driver Speaks English')),
                ('driver_speaks_fr', models.BooleanField(default=False, verbose_name='Driver Speaks French')),
                ('pickup_locations', models.JSONField(default=list, help_text='List of location names e.g. ["Zanzibar Airport", "Stone Town"]', verbose_name='Pickup Locations')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Toggle off during maintenance', verbose_name='Available for Booking')),
                ('is_active', models.BooleanField(default=False, help_text='True only when approval_status = approved', verbose_name='Active / Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Rental',
                'verbose_name_plural': 'Car Rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/photos/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carrental')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
