# Generated by Django 6.0.4 on 2026-04-14 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carrental')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Favourite',
                'verbose_name_plural': 'Saved Favourites',
                'constraints': [models.UniqueConstraint(condition=models.Q(('hotel__isnull', False)), fields=('user', 'hotel'), name='unique_user_hotel_favourite'), models.UniqueConstraint(condition=models.Q(('tour_package__isnull', False)), fields=('user', 'tour_package'), name='unique_user_tour_favourite'), models.UniqueConstraint(condition=models.Q(('car__isnull', False)), fields=('user', 'car'), name='unique_user_car_favourite')],
            },
        ),
    ]
