# Generated by Django 6.0.4 on 2026-04-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/photos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in Gallery Highlights section on homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order'],
            },
        ),
    ]
