# Generated by Django 6.0.4 on 2026-04-14 21:17

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('tour', 'Safari & Tour'), ('car', 'Car Rental')], max_length=10)),
                ('days_before_service', models.PositiveIntegerField(help_text='Cancellation must be made at least this many days before service date', verbose_name='Minimum Days Before Service')),
                ('refund_percentage', models.PositiveIntegerField(help_text='0 = no refund, 50 = half, 100 = full refund', verbose_name='Refund Percentage')),
                ('label_en', models.CharField(max_length=200, verbose_name='Label (English)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cancellation Policy',
                'verbose_name_plural': 'Cancellation Policies',
                'ordering': ['service_type', '-days_before_service'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.bookings.models.generate_booking_reference, max_length=20, unique=True, verbose_name='Booking Reference')),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('tour', 'Safari & Tour'), ('car', 'Car Rental')], max_length=10)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('num_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('num_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('num_days', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=200, null=True)),
                ('rental_mode', models.CharField(blank=True, choices=[('self_drive', 'Self Drive'), ('with_driver', 'With Driver')], max_length=15, null=True)),
                ('driver_licence_number', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('TZS', 'TZS'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('payment_mode', models.CharField(choices=[('pay_now', 'Pay Now (Online)'), ('pay_on_arrival', 'Pay on Arrival')], max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('pesapal_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pesapal_tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending_confirmation', max_length=25)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations_made', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cars.carrental')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.hotel')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotels.hotelroomtype')),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
