# Generated by Django 6.0.4 on 2026-04-14 21:18

from django.db import migrations


def seed_cancellation_policies(apps, schema_editor):
    CancellationPolicy = apps.get_model('bookings', 'CancellationPolicy')
    policies = [
        {'service_type': 'hotel', 'days_before_service': 14, 'refund_percentage': 100,
         'label_en': 'Full refund (14+ days before service)', 'is_active': True},
        {'service_type': 'hotel', 'days_before_service': 7, 'refund_percentage': 50,
         'label_en': '50% refund (7-13 days before service)', 'is_active': True},
        {'service_type': 'hotel', 'days_before_service': 0, 'refund_percentage': 0,
         'label_en': 'No refund (less than 7 days)', 'is_active': True},
        {'service_type': 'tour', 'days_before_service': 14, 'refund_percentage': 100,
         'label_en': 'Full refund (14+ days before service)', 'is_active': True},
        {'service_type': 'tour', 'days_before_service': 7, 'refund_percentage': 50,
         'label_en': '50% refund (7-13 days before service)', 'is_active': True},
        {'service_type': 'tour', 'days_before_service': 0, 'refund_percentage': 0,
         'label_en': 'No refund (less than 7 days)', 'is_active': True},
        {'service_type': 'car', 'days_before_service': 14, 'refund_percentage': 100,
         'label_en': 'Full refund (14+ days before service)', 'is_active': True},
        {'service_type': 'car', 'days_before_service': 7, 'refund_percentage': 50,
         'label_en': '50% refund (7-13 days before service)', 'is_active': True},
        {'service_type': 'car', 'days_before_service': 0, 'refund_percentage': 0,
         'label_en': 'No refund (less than 7 days)', 'is_active': True},
    ]
    for p in policies:
        CancellationPolicy.objects.get_or_create(
            service_type=p['service_type'],
            days_before_service=p['days_before_service'],
            defaults=p
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_cancellation_policies, migrations.RunPython.noop),
    ]