# Generated by Django 6.0.4 on 2026-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_cancellation_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='Snapshotted from the listing at booking time. False = non-refundable regardless of policy.', verbose_name='Is Refundable'),
        ),
    ]
