# Generated by Django 6.0.4 on 2026-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_refundable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allows_pets',
            field=models.BooleanField(default=False, help_text='Snapshotted from listing at booking time.', verbose_name='Pets Allowed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Adults'),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Children (2–12)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_infants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Infants (under 2)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_pets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pets'),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='Snapshotted from listing at booking time. False = non-refundable regardless of policy.', verbose_name='Is Refundable'),
        ),
    ]
